source 'https://rubygems.org'

gem 'activesupport', '~> 6.0'
gem 'smashing'
gem 'google-api-client', '< 0.4'
gem 'jwt', '~> 0.1.4'
gem 'launchy', '< 2.4'

## Uncomment this if you want to see use the twitter widget.
# gem 'twitter', '>= 5.9.0'